name: samling
favicon: null
layout_spectrum: 0.18766470300033689
typography_spectrum: 0.36955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#353434'
    - '#ff898b'
    - '#e00000'
    - '#5d9700'
  brandStrength: 0.8125
  lightness: 0.9626850849017501
  saturation: 0.2468815038446337
  rhythmicContrast: 0.35953698866069317
purpose: []
